### ISSUE TITLE
yourls-allow-aliases plugin not work for me

### ISSUE THREAD

**Issue by gitxxxa** [YOURLS/awesome-yourls#109] opened 2021-12-11 08:00 UTC
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://github.com/YOURLS/YOURLS/wiki/Troubleshooting-first-steps) guide.

### Version

1.8.2

### Description

Hello, the did all the steps as the instructions, but when I input short URLs with the alias domain in the browser, it goes directly to 404 page, I also tried this solution define( 'YOURLS_SITE', 'http://yourdomain.com' , 'http://aliaseddomain.com' ); but problems not solved,

Can anyone give some help? Thanks

### Expectation

expect to get the same result as the old domain name.

**Comment by dgw** [comment] 2021-12-11 08:07
Out of scope, and duplicate of upstream adigitalife/yourls-allow-aliases#7

**Closed by dgw** 2021-12-11 08:07 UTC
Labels: bug
